[tool.poetry]
name = "django-project"
version = "0.1.0"
description = ""
authors = ["Sabina9425 <visapa@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
