# Generated by Django 5.1.1 on 2024-09-10 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Введите дату производства продута",
                verbose_name="Дата производства продукта",
            ),
            preserve_default=False,
        ),
    ]
