# Generated by Django 5.1.1 on 2024-09-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.CharField(
                        help_text="Введите заголовок поста", max_length=50
                    ),
                ),
                ("slug", models.CharField(help_text="Введите slug", max_length=100)),
                (
                    "content",
                    models.TextField(
                        help_text="Введите заголовок поста", max_length=500
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="posts/preview",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания продукта"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="Признак публикации"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["created_at", "views"],
            },
        ),
    ]
