# Generated by Django 5.1.1 on 2024-09-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        help_text="Введите номер версии", max_length=50
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите название версии", max_length=50
                    ),
                ),
                (
                    "is_current_version",
                    models.BooleanField(
                        default=False, verbose_name="Признак текущей версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите продукт",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="версии",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["is_current_version", "version_number"],
            },
        ),
    ]
