# Generated by Django 5.1.1 on 2024-09-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите продукт",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.IntegerField(help_text="Введите номер версии"),
        ),
    ]
