# Generated by Django 4.2.2 on 2024-09-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "permissions": [
                    ("can_edit_product", "Can Edit Product"),
                    ("can_edit_description", "Can Edit Description"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
