# Generated by Django 4.2.2 on 2024-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_options_product_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(
                default="empty", help_text="Введите slug", max_length=100
            ),
        ),
    ]
